---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appdaemon-config
data:
  TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxYWQyYzRmMWUxYWU0YmVhOGJjMmQ2ODkzNTk2ZmZhNSIsImlhdCI6MTY3ODg2NDY1NSwiZXhwIjoxOTk0MjI0NjU1fQ.tFUAbDE6Ztxqm2ZKnKmNEn0BV-Ru1_e48HEJZx5YDGU
  HA_URL: http://localhost:8123
  DASH_URL: http://localhost:5050
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ha
  name: ha
spec:
  containers:
    - name: appdaemon
      image: docker.io/acockburn/appdaemon:latest
      volumeMounts:
        - mountPath: /etc/localtime
          name: etc-localtime
          readOnly: true
        - mountPath: /conf
          name: ha-appdaemon-conf
      ports:
        - containerPort: 5050
          hostPort: 5050
      envFrom:
        - configMapRef:
            name: appdaemon-config
            optional: false

  restartPolicy: OnFailure
  volumes:
    - name: etc-localtime
      hostPath:
        path: /etc/localtime
        type: File

    - name: ha-appdaemon-conf
      hostPath:
        path: /srv/ha/appdaemon/conf
        type: Directory
