---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-nc-caddyfile
data:
  Caddyfile: |
    {
      servers {
        metrics
      }
      admin :2019 {
        origins haze
      }
    }

    nc.paradise-liberty.ts.net {
      reverse_proxy 100.122.42.74:8088

      tls /certs/nc.crt /certs/nc.key

      redir /.well-known/carddav /remote.php/carddav 301
      redir /.well-known/caldav /remote.php/caldav 301

      header {
        Strict-Transport-Security max-age=15552000;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: caddy-nc
  name: caddy-nc
spec:
  containers:
    - name: caddy
      image: docker.io/library/caddy:latest
      volumeMounts:
        - mountPath: /data
          name: caddy-nc-data
        - mountPath: /config
          name: caddy-nc-config
        - mountPath: /certs
          name: caddy-nc-certs
          readOnly: true
        - mountPath: /etc/caddy
          name: caddy-nc-caddyfile

    - name: tailscale
      image: docker.io/tailscale/tailscale:latest
      volumeMounts:
        - mountPath: /certs
          name: caddy-nc-certs
        - mountPath: /state
          name: caddy-nc-tailscale
      env:
        - name: TS_AUTH_ONCE
          value: true
        - name: TS_HOSTNAME
          value: nc.paradise-liberty.ts.net
        - name: TS_STATE_DIR
          value: /state

  restartPolicy: OnFailure

  volumes:
    - name: caddy-nc-data
      hostPath:
        path: /srv/caddy-nc/data
        type: Directory
    - name: caddy-nc-config
      hostPath:
        path: /srv/caddy-nc/config
        type: Directory
    - name: caddy-nc-certs
      hostPath:
        path: /srv/caddy-nc/certs
        type: Directory
    - name: caddy-nc-tailscale
      hostPath:
        path: /srv/caddy-nc/tailscale_state
        type: Directory
    - name: caddy-nc-caddyfile
      configMap:
        defaultMode: 420
        name: caddy-nc-caddyfile
