---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg0
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  TZ: Asia/Taipei
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pg0
  name: pg0
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:16.1
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      envFrom:
        - configMapRef:
            name: pg0
            optional: false
    - name: postgres-exporter
      image: quay.io/prometheuscommunity/postgres-exporter
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  restartPolicy: OnFailure
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data
